### ISSUE TITLE
Ability to run native queries

### ISSUE THREAD

**Issue by enumag** [driftphp/reactphp-dbal#7]
With Doctrine's DBAL connection it's a good thing that you're not limited to using the QueryBuilder - it can help you build most queries but when you need something platform-specific you can just pass plain SQL string.

Drift\DBAL\Connection limits the user to QueryBuilder queries. In my opinion there should be a method to execute native queries as well for any edge-cases when QueryBuilder is not an option due to its limits.

**Comment by mmoreram** [comment]
Working on that :+1: 

Thanks!

**Comment by mmoreram** [comment]
You can see a small implementation for that feature here - https://github.com/driftphp/reactphp-dbal/pull/9

**Comment by mmoreram** [comment]
You can already do that. Remember that you must follow the `?` format for parametrization.

```php
$connection->queryBySQL($sql, $params);
```
